### ISSUE TITLE
Tell us a bit more

### ISSUE THREAD

**Issue by Vartkat** [jchonig/docker-nut-cgi#1]
Hello,

this seems to be what I'm looking for as I want to see the nut webserver from another machine.

Is that it ?
If so can you tell how to configure things so that when we go to this docker web server from a web browser we see tha nut web interface (knowing that nut is running on another local server)?

**Comment by jchonig** [comment]
The purpose of this container is to allow nginx running in a container to easily run nut-cgi w/o installing anything on the host system.

All the configuration is documented in the README.md.
